/**
 * Sample destinations and packages for `npm run seed`.
 * Prices, visa notes and seasons are sensible starting points; review them in the admin panel before going live.
 */
import type { Companion, DestinationCollection } from '../common/constants';
import type { TitleStyle } from '../destinations/destination.schema';

export interface SeedDestination {
  slug: string;
  name: string;
  country: string;
  tagline: string;
  titleStyle: TitleStyle;
  collections: DestinationCollection[];
  summary: string;
  description: string;
  bestTime: string;
  visa: string;
  minNights: number;
  maxNights: number;
  startingPrice: number;
  highlights: string[];
  cities: [name: string, nights: number, note?: string][];
}

export interface SeedPackage {
  destination: string;
  title: string;
  summary: string;
  companions: Companion[];
  cities: [name: string, nights: number][];
  price: number;
  originalPrice?: number;
  badge?: string;
  featured?: boolean;
  highlights: string[];
  inclusions: string[];
  exclusions: string[];
  itinerary: [title: string, description: string][];
}

const STD_EXCLUSIONS = ['International flights (we can book them for you)', 'Visa fees', 'Personal expenses and tips', 'Travel insurance (recommended)'];
const DOMESTIC_EXCLUSIONS = ['Flights or trains to the starting point', 'Personal expenses and tips', 'Entry tickets not listed'];

export const SEED_DESTINATIONS: SeedDestination[] = [
  {
    slug: 'finland',
    name: 'Finland',
    country: 'Finland',
    tagline: 'Chase the northern lights',
    titleStyle: 'serif',
    collections: ['featured', 'international'],
    summary: 'Glass igloos, husky trails and skies that dance green over Lapland.',
    description:
      'Finnish Lapland is one of the most reliable places on Earth to see the aurora borealis. Days are for husky and reindeer safaris across frozen lakes, snowmobiling through silent forests and a visit to Santa Claus Village on the Arctic Circle. Nights are for sauna, hot chocolate and watching the sky light up from a glass-roofed igloo.\n\nWe pace the trip so you get several dark, clear nights in the north, which is what matters most for aurora sightings.',
    bestTime: 'December to March for auroras and snow',
    visa: 'Schengen visa required for Indian passport holders',
    minNights: 5,
    maxNights: 8,
    startingPrice: 175000,
    highlights: ['Aurora hunting from a glass igloo', 'Husky and reindeer safaris', 'Santa Claus Village on the Arctic Circle', 'Traditional Finnish sauna and ice-hole dip'],
    cities: [['Helsinki', 1, 'Design district and harbour'], ['Rovaniemi', 3, 'Arctic Circle and Santa Claus Village'], ['Saariselkä', 2, 'Dark skies for aurora hunting']],
  },
  {
    slug: 'switzerland',
    name: 'Switzerland',
    country: 'Switzerland',
    tagline: 'Beauty of central Europe',
    titleStyle: 'script',
    collections: ['featured', 'international', 'honeymoon'],
    summary: 'Snow peaks, glacier trains and lakeside towns straight off a postcard.',
    description:
      'Switzerland packs lakes, glaciers and chocolate-box villages into a country you can cross by train in a day. Ride the cogwheel railway to Jungfraujoch, the “Top of Europe”, cruise Lake Lucerne, float up Mt Titlis on a rotating cable car and wake up to the Matterhorn in car-free Zermatt.\n\nThe Swiss Travel Pass makes it effortless: one pass covers trains, boats and most city transport.',
    bestTime: 'April to October for green valleys; December to March for snow',
    visa: 'Schengen visa required for Indian passport holders',
    minNights: 6,
    maxNights: 10,
    startingPrice: 165000,
    highlights: ['Jungfraujoch, the Top of Europe', 'Mt Titlis rotating cable car', 'Lake Lucerne cruise', 'Glacier Express panorama train'],
    cities: [['Zurich', 1], ['Lucerne', 2, 'Chapel Bridge and Mt Titlis'], ['Interlaken', 3, 'Jungfraujoch and Grindelwald'], ['Zermatt', 2, 'Matterhorn views']],
  },
  {
    slug: 'japan',
    name: 'Japan',
    country: 'Japan',
    tagline: 'Land of the rising sun',
    titleStyle: 'caps',
    collections: ['featured', 'international'],
    summary: 'Neon Tokyo, temple Kyoto and bullet trains past Mt Fuji.',
    description:
      'Japan is where ancient and futuristic sit side by side. Wander Shibuya’s famous crossing, then slow down in Kyoto’s bamboo groves and thousand-gate shrines. Soak in an onsen with Mt Fuji on the horizon at Hakone, and eat your way through Osaka’s street-food lanes.\n\nWe plan around the JR Pass and the seasons: cherry blossom in spring, fiery maples in autumn.',
    bestTime: 'March to April for cherry blossom; October to November for autumn colours',
    visa: 'e-Visa available for Indian passport holders',
    minNights: 6,
    maxNights: 11,
    startingPrice: 140000,
    highlights: ['Shinkansen bullet train', 'Mt Fuji views from Hakone', 'Fushimi Inari and Arashiyama in Kyoto', 'Osaka street food in Dotonbori'],
    cities: [['Tokyo', 3], ['Hakone', 1, 'Onsen and Mt Fuji views'], ['Kyoto', 3], ['Osaka', 2]],
  },
  {
    slug: 'maldives',
    name: 'Maldives',
    country: 'Maldives',
    tagline: 'Create memories in',
    titleStyle: 'script',
    collections: ['featured', 'international', 'visa-free', 'honeymoon'],
    summary: 'Overwater villas, glass-clear lagoons and reefs at your doorstep.',
    description:
      'Just a short flight from India, the Maldives is a string of coral islands where each resort has its own island. Wake up over the lagoon, snorkel with turtles and reef sharks straight off your deck, and end the day with a sandbank dinner under the stars.\n\nWe match you to the right resort for your budget and style, from lively family islands to adults-only hideaways, and sort seaplane or speedboat transfers.',
    bestTime: 'November to April (dry season)',
    visa: 'Free visa on arrival for Indian passport holders',
    minNights: 3,
    maxNights: 7,
    startingPrice: 65000,
    highlights: ['Overwater villa stay', 'Snorkelling with turtles and manta rays', 'Sunset dolphin cruise', 'Private sandbank dinner'],
    cities: [['North Malé Atoll', 2, 'Speedboat resorts'], ['Ari Atoll', 2, 'Seaplane resorts and whale sharks']],
  },
  {
    slug: 'bali',
    name: 'Bali',
    country: 'Indonesia',
    tagline: 'Cultural paradise',
    titleStyle: 'caps',
    collections: ['featured', 'international', 'honeymoon'],
    summary: 'Rice terraces, lake temples, beach clubs and the warmest welcome.',
    description:
      'Bali blends jungle, culture and coast. In Ubud, walk the Tegallalang rice terraces, watch a Kecak fire dance and swing over the valley. Visit the lake temple of Ulun Danu Beratan, then head south for Seminyak’s sunsets or a day trip to the cliffs of Nusa Penida.\n\nIt suits honeymooners and friends’ trips alike, with private-pool villas at very reasonable prices.',
    bestTime: 'April to October (dry season)',
    visa: 'Visa on arrival or e-VOA for Indian passport holders',
    minNights: 5,
    maxNights: 9,
    startingPrice: 55000,
    highlights: ['Tegallalang rice terraces', 'Ulun Danu Beratan lake temple', 'Nusa Penida cliffs day trip', 'Private-pool villa stays'],
    cities: [['Ubud', 3, 'Jungle, temples and rice fields'], ['Seminyak', 2, 'Beaches and sunsets'], ['Nusa Penida', 1]],
  },
  {
    slug: 'thailand',
    name: 'Thailand',
    country: 'Thailand',
    tagline: 'The kingdom of',
    titleStyle: 'bold',
    collections: ['international', 'visa-free'],
    summary: 'Limestone islands, night markets and some of the best food on Earth.',
    description:
      'Thailand does everything well and does it affordably. Hop between the Phi Phi islands on a longtail boat, kayak through Krabi’s mangroves, watch the sun go down at Phuket’s Promthep Cape, then trade beaches for Bangkok’s temples, rooftop bars and night markets.\n\nGreat for couples, families and first-time international travellers.',
    bestTime: 'November to April',
    visa: 'Visa-free entry for Indian passport holders (check the latest rules before travel)',
    minNights: 4,
    maxNights: 9,
    startingPrice: 38000,
    highlights: ['Phi Phi and Maya Bay by longtail boat', 'Krabi’s Railay Beach and Four Islands', 'Bangkok temples and night markets', 'Thai cooking class'],
    cities: [['Bangkok', 2], ['Pattaya', 2], ['Phuket', 3], ['Krabi', 3]],
  },
  {
    slug: 'singapore',
    name: 'Singapore',
    country: 'Singapore',
    tagline: 'The Lion City',
    titleStyle: 'caps',
    collections: ['international'],
    summary: 'Gardens of the future, Sentosa thrills and hawker-centre feasts.',
    description:
      'Singapore is the easiest international holiday there is: spotless, safe and packed with things to do. Gardens by the Bay and its Supertrees, Universal Studios and the S.E.A. Aquarium on Sentosa, the Night Safari, and hawker centres where a Michelin-starred meal costs a few dollars.\n\nPerfect for families and for a short first trip abroad.',
    bestTime: 'Year-round; February to April is driest',
    visa: 'Visa required; applied online through authorised agents (we help)',
    minNights: 3,
    maxNights: 6,
    startingPrice: 60000,
    highlights: ['Gardens by the Bay light show', 'Universal Studios Singapore', 'Night Safari', 'Marina Bay Sands SkyPark'],
    cities: [['Singapore', 3], ['Sentosa', 1]],
  },
  {
    slug: 'dubai',
    name: 'Dubai',
    country: 'United Arab Emirates',
    tagline: 'City of gold',
    titleStyle: 'serif',
    collections: ['international'],
    summary: 'Desert dunes, record-breaking skylines and world-class shopping.',
    description:
      'Dubai is a four-hour flight from most Indian cities and delivers big: the view from the Burj Khalifa, a dune-bashing desert safari with a barbecue dinner under the stars, a dhow cruise along the creek and the gold and spice souks of old Dubai. Add a day in Abu Dhabi for the Sheikh Zayed Grand Mosque and Ferrari World.',
    bestTime: 'November to March',
    visa: 'Visa required; e-visa or visa on arrival for eligible Indian passport holders',
    minNights: 3,
    maxNights: 6,
    startingPrice: 50000,
    highlights: ['At the Top, Burj Khalifa', 'Desert safari with BBQ dinner', 'Dhow cruise at Marina', 'Abu Dhabi day trip'],
    cities: [['Dubai', 4], ['Abu Dhabi', 1]],
  },
  {
    slug: 'vietnam',
    name: 'Vietnam',
    country: 'Vietnam',
    tagline: 'Timeless charm of',
    titleStyle: 'serif',
    collections: ['international', 'offbeat'],
    summary: 'Emerald bays, lantern-lit old towns and bowls of pho at dawn.',
    description:
      'Vietnam runs from misty northern karsts to the buzzing south. Cruise overnight among the limestone islands of Ha Long Bay, walk Hanoi’s Old Quarter, cross the Golden Bridge near Da Nang, drift through lantern-lit Hoi An and crawl through the Cu Chi tunnels outside Ho Chi Minh City.\n\nExcellent value, with direct flights from several Indian cities.',
    bestTime: 'February to April and August to October',
    visa: 'e-Visa available for Indian passport holders',
    minNights: 6,
    maxNights: 11,
    startingPrice: 60000,
    highlights: ['Overnight Ha Long Bay cruise', 'Hoi An lantern old town', 'Golden Bridge at Ba Na Hills', 'Cu Chi tunnels'],
    cities: [['Hanoi', 2], ['Ha Long Bay', 1], ['Da Nang & Hoi An', 3], ['Ho Chi Minh City', 2]],
  },
  {
    slug: 'kenya',
    name: 'Kenya',
    country: 'Kenya',
    tagline: 'Masai migration',
    titleStyle: 'caps',
    collections: ['international', 'offbeat'],
    summary: 'Big-five safaris and the greatest wildlife show on the planet.',
    description:
      'Every year, over a million wildebeest and zebra cross from Tanzania into Kenya’s Maasai Mara. Watch the river crossings, track lions and cheetahs on game drives, float over the savannah in a hot-air balloon at sunrise and visit a Maasai village. Finish with a boat safari among hippos on Lake Naivasha.',
    bestTime: 'July to October for the Great Migration',
    visa: 'Electronic Travel Authorisation (eTA) required',
    minNights: 5,
    maxNights: 8,
    startingPrice: 175000,
    highlights: ['Game drives in the Maasai Mara', 'Great Migration river crossings', 'Hot-air balloon safari', 'Lake Naivasha boat ride'],
    cities: [['Nairobi', 1], ['Maasai Mara', 3], ['Lake Naivasha', 1]],
  },
  {
    slug: 'sri-lanka',
    name: 'Sri Lanka',
    country: 'Sri Lanka',
    tagline: 'Fall in love with',
    titleStyle: 'script',
    collections: ['international', 'visa-free'],
    summary: 'Rock fortresses, tea country trains and golden southern beaches.',
    description:
      'Sri Lanka is small enough to see a lot in a week. Climb the Sigiriya rock fortress, visit the Temple of the Tooth in Kandy, ride the famous blue train through tea country to Ella, spot leopards in Yala and slow down on the beaches of Bentota and Galle.\n\nA great fit for families and for travellers who want culture, nature and beaches in one trip.',
    bestTime: 'December to April for the west and south coasts',
    visa: 'Free ETA for Indian passport holders (check the latest rules before travel)',
    minNights: 5,
    maxNights: 9,
    startingPrice: 45000,
    highlights: ['Sigiriya rock fortress', 'Kandy to Ella scenic train', 'Temple of the Tooth', 'Galle Fort and southern beaches'],
    cities: [['Sigiriya', 1], ['Kandy', 2], ['Nuwara Eliya', 1], ['Bentota', 2]],
  },
  {
    slug: 'malaysia',
    name: 'Malaysia',
    country: 'Malaysia',
    tagline: 'The hidden gem of Asia',
    titleStyle: 'bold',
    collections: ['international', 'visa-free'],
    summary: 'Twin towers, cool highlands and the duty-free beaches of Langkawi.',
    description:
      'Malaysia pairs a modern capital with easy-going islands. See Kuala Lumpur from the Petronas Towers skybridge, climb the steps to the Batu Caves, day-trip to the highlands of Genting, then fly to Langkawi for island hopping, the Sky Bridge and duty-free shopping.',
    bestTime: 'March to October',
    visa: 'Visa-free entry for Indian passport holders (check the latest rules before travel)',
    minNights: 4,
    maxNights: 7,
    startingPrice: 45000,
    highlights: ['Petronas Twin Towers', 'Batu Caves', 'Langkawi Sky Bridge', 'Island hopping in Langkawi'],
    cities: [['Kuala Lumpur', 2], ['Langkawi', 3]],
  },
  {
    slug: 'mauritius',
    name: 'Mauritius',
    country: 'Mauritius',
    tagline: 'The incredible island',
    titleStyle: 'bold',
    collections: ['international', 'visa-free', 'honeymoon'],
    summary: 'Turquoise lagoons, Le Morne mountain and a warm Indian welcome.',
    description:
      'Ringed by coral reef and turquoise lagoons, Mauritius feels familiar and exotic at once. Catamaran to Île aux Cerfs, swim with dolphins off the west coast, see the seven-coloured earths of Chamarel and the underwater “waterfall” illusion off Le Morne. Resorts here are some of the finest in the Indian Ocean.',
    bestTime: 'May to December',
    visa: 'Visa-free on arrival for Indian passport holders',
    minNights: 5,
    maxNights: 8,
    startingPrice: 85000,
    highlights: ['Catamaran cruise to Île aux Cerfs', 'Chamarel seven-coloured earths', 'Dolphin swim at Tamarin Bay', 'Le Morne Brabant'],
    cities: [['Grand Baie', 3, 'North coast'], ['Le Morne', 3, 'South-west coast']],
  },
  {
    slug: 'santorini',
    name: 'Greece',
    country: 'Greece',
    tagline: 'Sunsets of the Aegean',
    titleStyle: 'serif',
    collections: ['international', 'honeymoon'],
    summary: 'Blue domes, caldera sunsets and island-hopping by ferry.',
    description:
      'Start with the Acropolis and the tavernas of Plaka in Athens, then ferry to Santorini for whitewashed villages, volcanic beaches and the world’s most famous sunset in Oia. Finish on Mykonos with its windmills and beach clubs. A romantic classic that also suits groups of friends.',
    bestTime: 'May to October',
    visa: 'Schengen visa required for Indian passport holders',
    minNights: 6,
    maxNights: 10,
    startingPrice: 155000,
    highlights: ['Oia sunset in Santorini', 'Caldera catamaran cruise', 'The Acropolis', 'Mykonos windmills and Little Venice'],
    cities: [['Athens', 2], ['Santorini', 3], ['Mykonos', 2]],
  },
  {
    slug: 'kerala',
    name: 'Kerala',
    country: 'India',
    tagline: "God's own country",
    titleStyle: 'caps',
    collections: ['domestic', 'honeymoon'],
    summary: 'Houseboats, tea hills, spice gardens and Ayurveda.',
    description:
      'Kerala moves at its own gentle pace. Walk through Fort Kochi’s Chinese fishing nets, wake up to misty tea estates in Munnar, go spice-garden hopping and bamboo rafting in Thekkady, then spend a night floating on a private houseboat through the Alleppey backwaters. Add a few beach days in Varkala if you like.',
    bestTime: 'September to March',
    visa: 'No visa needed for Indian citizens',
    minNights: 4,
    maxNights: 8,
    startingPrice: 22000,
    highlights: ['Overnight houseboat in Alleppey', 'Munnar tea estates', 'Periyar wildlife and spice gardens', 'Kathakali performance in Kochi'],
    cities: [['Kochi', 1], ['Munnar', 2], ['Thekkady', 1], ['Alleppey', 1]],
  },
  {
    slug: 'rajasthan',
    name: 'Rajasthan',
    country: 'India',
    tagline: 'Land of kings',
    titleStyle: 'serif',
    collections: ['domestic'],
    summary: 'Palaces on lakes, desert forts and royal heritage stays.',
    description:
      'Rajasthan is India at its most regal. Explore the Amber Fort and pink city of Jaipur, stand under the walls of Mehrangarh in blue Jodhpur, watch the sunset over Lake Pichola in Udaipur and sleep under the stars in the Thar desert near Jaisalmer. Heritage havelis and palace hotels make the stays part of the story.',
    bestTime: 'October to March',
    visa: 'No visa needed for Indian citizens',
    minNights: 5,
    maxNights: 10,
    startingPrice: 28000,
    highlights: ['Amber Fort, Jaipur', 'Mehrangarh Fort, Jodhpur', 'Lake Pichola boat ride, Udaipur', 'Desert camp in Jaisalmer'],
    cities: [['Jaipur', 2], ['Jodhpur', 2], ['Udaipur', 2], ['Jaisalmer', 2]],
  },
  {
    slug: 'kashmir',
    name: 'Kashmir',
    country: 'India',
    tagline: 'Paradise on earth',
    titleStyle: 'script',
    collections: ['domestic', 'honeymoon'],
    summary: 'Shikara rides on Dal Lake, meadows of Gulmarg and Pahalgam.',
    description:
      'Stay on a carved-wood houseboat on Dal Lake and glide past floating markets on a shikara. Ride the Gulmarg gondola, one of the highest in the world, walk through the pine valleys of Pahalgam and see the glaciers at Sonamarg. In winter, it becomes India’s favourite snow destination.',
    bestTime: 'March to October; December to February for snow',
    visa: 'No visa needed for Indian citizens',
    minNights: 4,
    maxNights: 7,
    startingPrice: 25000,
    highlights: ['Houseboat stay and shikara ride on Dal Lake', 'Gulmarg gondola', 'Betaab Valley, Pahalgam', 'Mughal gardens of Srinagar'],
    cities: [['Srinagar', 2], ['Gulmarg', 1], ['Pahalgam', 2]],
  },
  {
    slug: 'andaman',
    name: 'Andaman Islands',
    country: 'India',
    tagline: 'Barefoot paradise',
    titleStyle: 'caps',
    collections: ['domestic', 'honeymoon'],
    summary: 'Powder-white beaches, first dives and island-hopping ferries.',
    description:
      'The Andamans have some of Asia’s best beaches without leaving India. Radhanagar Beach on Havelock (Swaraj Dweep) regularly tops world lists, the reefs are perfect for a first scuba dive, and Neil Island (Shaheed Dweep) is made for cycling and sunsets. Start in Port Blair with the Cellular Jail light-and-sound show.',
    bestTime: 'October to May',
    visa: 'No visa needed for Indian citizens',
    minNights: 4,
    maxNights: 7,
    startingPrice: 32000,
    highlights: ['Radhanagar Beach, Havelock', 'Try-scuba dive at Elephant Beach', 'Natural rock bridge, Neil Island', 'Cellular Jail light and sound show'],
    cities: [['Port Blair', 1], ['Havelock', 3], ['Neil Island', 1]],
  },
  {
    slug: 'bhutan',
    name: 'Bhutan',
    country: 'Bhutan',
    tagline: 'Land of happiness',
    titleStyle: 'serif',
    collections: ['domestic', 'offbeat'],
    summary: 'Cliffside monasteries, prayer flags and a kingdom that measures happiness.',
    description:
      'Bhutan is a Himalayan kingdom that protects its culture and forests fiercely. Hike to the cliffside Tiger’s Nest monastery above Paro, cross the Dochula pass with its 108 chortens, visit the riverside Punakha Dzong and explore the capital, Thimphu, where there is not a single traffic light.',
    bestTime: 'March to May and September to November',
    visa: 'No visa for Indian citizens; entry permit on arrival (Sustainable Development Fee applies)',
    minNights: 5,
    maxNights: 8,
    startingPrice: 48000,
    highlights: ['Tiger’s Nest (Paro Taktsang) hike', 'Punakha Dzong', 'Dochula Pass', 'Buddha Dordenma, Thimphu'],
    cities: [['Thimphu', 2], ['Punakha', 1], ['Paro', 2]],
  },
  {
    slug: 'ladakh',
    name: 'Ladakh',
    country: 'India',
    tagline: 'Where the road ends',
    titleStyle: 'bold',
    collections: ['domestic', 'offbeat'],
    summary: 'High passes, blue lakes and monasteries under enormous skies.',
    description:
      'Ladakh is a high-altitude desert of monasteries, sand dunes and impossible blues. Acclimatise in Leh, visit Thiksey and Hemis monasteries, drive over Khardung La to the Nubra Valley’s double-humped camels, and spend a night by the shifting colours of Pangong Tso.\n\nWe build in rest days for altitude, which makes a real difference.',
    bestTime: 'May to September',
    visa: 'No visa needed; Inner Line Permit required for some areas (we arrange it)',
    minNights: 5,
    maxNights: 9,
    startingPrice: 35000,
    highlights: ['Pangong Tso lakeside camp', 'Khardung La pass', 'Nubra Valley dunes', 'Thiksey Monastery'],
    cities: [['Leh', 3], ['Nubra Valley', 1], ['Pangong', 1]],
  },
];

export const SEED_PACKAGES: SeedPackage[] = [
  {
    destination: 'thailand',
    title: 'Couple Retreat: 7 Nights in Krabi and Phuket',
    summary: 'Island hopping, sunset viewpoints and beachfront resorts on the Andaman coast.',
    companions: ['couple'],
    cities: [['Krabi', 4], ['Phuket', 3]],
    price: 98500,
    originalPrice: 112000,
    badge: 'Bestseller',
    featured: true,
    highlights: ['Four Islands tour by longtail', 'Phi Phi and Maya Bay speedboat day', 'Promthep Cape sunset', 'Couple spa session'],
    inclusions: ['7 nights in 4★ beachfront resorts with breakfast', 'All airport and inter-city transfers', 'Four Islands and Phi Phi tours with lunch', 'One 60-minute couple spa', 'Local SIM card'],
    exclusions: STD_EXCLUSIONS,
    itinerary: [
      ['Arrive in Krabi', 'Private transfer to your Ao Nang resort. Evening walk along the beach promenade.'],
      ['Four Islands by longtail', 'Visit Phra Nang Cave Beach, Chicken Island and Tup Island with snorkelling stops and lunch.'],
      ['Railay at your pace', 'Longtail to Railay for cliffs, lagoons and rock climbing or simply a lazy beach day.'],
      ['Krabi free day', 'Optional Emerald Pool and hot springs, or a Thai cooking class.'],
      ['Transfer to Phuket', 'Scenic drive to Phuket. Couple spa in the evening.'],
      ['Phi Phi Islands', 'Speedboat to Maya Bay, Pileh Lagoon and Monkey Beach with lunch on Phi Phi Don.'],
      ['Old Town and sunset', 'Colourful Old Phuket Town, Big Buddha and sunset at Promthep Cape.'],
      ['Fly home', 'Breakfast and airport transfer.'],
    ],
  },
  {
    destination: 'thailand',
    title: 'Family Fun: 5 Nights in Bangkok and Pattaya',
    summary: 'Coral Island, Safari World and night markets, paced for children.',
    companions: ['family', 'friends'],
    cities: [['Pattaya', 3], ['Bangkok', 2]],
    price: 34900,
    highlights: ['Coral Island speedboat trip', 'Safari World and Marine Park', 'Chao Phraya dinner cruise', 'Sanctuary of Truth'],
    inclusions: ['5 nights in family-friendly 4★ hotels with breakfast', 'All transfers in a private vehicle', 'Coral Island tour with lunch', 'Safari World tickets with lunch', 'Dinner cruise'],
    exclusions: STD_EXCLUSIONS,
    itinerary: [
      ['Arrive and drive to Pattaya', 'Airport pick-up and transfer to Pattaya. Evening Alcazar show.'],
      ['Coral Island', 'Speedboat to Koh Larn for beaches and optional parasailing.'],
      ['Sanctuary of Truth and Nong Nooch', 'The all-wood temple and the tropical gardens.'],
      ['To Bangkok', 'Transfer to Bangkok, temple tour and evening Chao Phraya dinner cruise.'],
      ['Safari World', 'Full day at Safari World and Marine Park.'],
      ['Fly home', 'Breakfast and airport transfer.'],
    ],
  },
  {
    destination: 'maldives',
    title: 'Overwater Honeymoon: 4 Nights in the Maldives',
    summary: 'Beach villa to overwater villa, with a sandbank dinner for two.',
    companions: ['couple'],
    cities: [['North Malé Atoll', 4]],
    price: 124000,
    originalPrice: 139000,
    badge: 'Honeymoon pick',
    featured: true,
    highlights: ['2 nights beach villa + 2 nights overwater villa', 'Private sandbank dinner', 'Sunset dolphin cruise', 'Honeymoon cake and flowers'],
    inclusions: ['4 nights in a 5★ resort, half board', 'Return speedboat transfers', 'One private sandbank dinner', 'Sunset dolphin cruise', 'Honeymoon inclusions'],
    exclusions: STD_EXCLUSIONS,
    itinerary: [
      ['Welcome to paradise', 'Speedboat from Malé to your resort. Check in to your beach villa.'],
      ['Reef day', 'House-reef snorkelling with turtles, then a sunset dolphin cruise.'],
      ['Move over the water', 'Shift to your overwater villa. Evening sandbank dinner for two.'],
      ['Spa and slow', 'Free day for the spa, paddle-boarding or simply the hammock.'],
      ['Farewell', 'Breakfast and speedboat to Malé.'],
    ],
  },
  {
    destination: 'bali',
    title: 'Bali Bliss: 6 Nights in Ubud and Seminyak',
    summary: 'Jungle villa, temples and waterfalls, then beach sunsets.',
    companions: ['couple', 'friends'],
    cities: [['Ubud', 3], ['Seminyak', 3]],
    price: 62500,
    highlights: ['Private-pool villa in Ubud', 'Kintamani volcano and coffee plantation', 'Nusa Penida day trip', 'Uluwatu Kecak fire dance'],
    inclusions: ['6 nights (private-pool villa in Ubud, 4★ in Seminyak) with breakfast', 'All transfers and sightseeing in a private car', 'Nusa Penida tour', 'Uluwatu Kecak dance tickets'],
    exclusions: STD_EXCLUSIONS,
    itinerary: [
      ['Arrive in Bali', 'Transfer to your Ubud pool villa.'],
      ['Ubud highlights', 'Tegallalang rice terraces, jungle swing, Tirta Empul temple.'],
      ['Kintamani', 'Mt Batur volcano views, a coffee plantation and Ulun Danu Beratan temple.'],
      ['To Seminyak', 'Transfer via Tanah Lot temple for sunset.'],
      ['Nusa Penida', 'Kelingking Beach, Broken Beach and Angel’s Billabong.'],
      ['Uluwatu', 'Cliff-top temple and the Kecak fire dance at sunset.'],
      ['Fly home', 'Breakfast and airport transfer.'],
    ],
  },
  {
    destination: 'switzerland',
    title: 'Swiss Grand Tour: 8 Nights',
    summary: 'Lucerne, Interlaken and Zermatt with a Swiss Travel Pass.',
    companions: ['couple', 'family', 'seniors'],
    cities: [['Lucerne', 3], ['Interlaken', 3], ['Zermatt', 2]],
    price: 235000,
    originalPrice: 259000,
    featured: true,
    highlights: ['Jungfraujoch excursion', 'Mt Titlis with Ice Flyer', 'Lake Lucerne cruise', 'Gornergrat railway to Matterhorn views'],
    inclusions: ['8 nights in 3★/4★ hotels with breakfast', '8-day Swiss Travel Pass (2nd class)', 'Jungfraujoch and Mt Titlis tickets', 'Gornergrat railway', 'Schengen visa assistance'],
    exclusions: ['International flights', 'Visa fees', 'Lunches and dinners', 'Personal expenses'],
    itinerary: [
      ['Zurich to Lucerne', 'Train to Lucerne. Walk the Chapel Bridge and old town.'],
      ['Mt Titlis', 'Rotating cable car, glacier cave and Ice Flyer.'],
      ['Lake Lucerne', 'Boat cruise and optional Mt Pilatus.'],
      ['To Interlaken', 'Scenic Golden Pass train to Interlaken.'],
      ['Jungfraujoch', 'Cogwheel train to the Top of Europe.'],
      ['Grindelwald First', 'Cliff walk and optional First Flyer; evening in Interlaken.'],
      ['To Zermatt', 'Train to car-free Zermatt, village stroll.'],
      ['Gornergrat', 'Railway to 3,089 m for the Matterhorn up close.'],
      ['Depart', 'Train to Zurich airport.'],
    ],
  },
  {
    destination: 'japan',
    title: 'Japan Highlights: 9 Nights Tokyo to Osaka',
    summary: 'The classic golden route with a night at a Hakone onsen ryokan.',
    companions: ['friends', 'couple', 'solo'],
    cities: [['Tokyo', 4], ['Hakone', 1], ['Kyoto', 2], ['Osaka', 2]],
    price: 185000,
    highlights: ['7-day JR Pass', 'Ryokan night with onsen in Hakone', 'Fushimi Inari and Arashiyama', 'Nara deer park day trip'],
    inclusions: ['9 nights in 3★ hotels + 1 ryokan night with dinner', '7-day JR Pass', 'Hakone Free Pass', 'Airport transfers by train', 'Pocket Wi-Fi'],
    exclusions: STD_EXCLUSIONS,
    itinerary: [
      ['Arrive in Tokyo', 'Airport train to your hotel in Shinjuku.'],
      ['Modern Tokyo', 'Shibuya Crossing, Harajuku, Meiji Shrine and Shinjuku by night.'],
      ['Old Tokyo', 'Asakusa, Senso-ji and a Sumida river cruise to Odaiba.'],
      ['Day trip', 'Nikko or Kamakura, your choice.'],
      ['Hakone', 'Lake Ashi cruise, ropeway and ryokan onsen with Mt Fuji views.'],
      ['Kyoto', 'Shinkansen to Kyoto. Evening in Gion.'],
      ['Kyoto classics', 'Fushimi Inari, Kinkaku-ji and Arashiyama bamboo grove.'],
      ['Osaka', 'Nara deer park on the way; evening in Dotonbori.'],
      ['Osaka free day', 'Osaka Castle or Universal Studios Japan.'],
      ['Depart', 'Train to Kansai airport.'],
    ],
  },
  {
    destination: 'finland',
    title: 'Lapland Aurora Escape: 6 Nights',
    summary: 'Glass igloo nights, husky safari and Santa Claus Village.',
    companions: ['couple', 'friends', 'family'],
    cities: [['Rovaniemi', 3], ['Saariselkä', 3]],
    price: 265000,
    badge: 'Once in a lifetime',
    highlights: ['2 nights in a glass igloo', 'Husky safari', 'Reindeer farm visit', 'Guided aurora hunt by snowmobile'],
    inclusions: ['6 nights incl. 2 glass-igloo nights, half board', 'Thermal winter clothing', 'Husky, reindeer and snowmobile safaris', 'Guided aurora hunt', 'All transfers'],
    exclusions: STD_EXCLUSIONS,
    itinerary: [
      ['Arrive Rovaniemi', 'Transfer to your hotel and collect thermal gear.'],
      ['Santa Claus Village', 'Cross the Arctic Circle and meet Santa.'],
      ['Husky safari', 'Mush your own sled through snowy forest.'],
      ['To Saariselkä', 'Drive north to the glass igloos.'],
      ['Reindeer and aurora', 'Reindeer farm by day; guided aurora hunt by night.'],
      ['Snowmobile day', 'Snowmobile to a wilderness hut for lunch by the fire.'],
      ['Depart', 'Transfer to Ivalo airport.'],
    ],
  },
  {
    destination: 'dubai',
    title: 'Dubai Family Holiday: 5 Nights',
    summary: 'Desert safari, theme parks and Burj Khalifa views.',
    companions: ['family', 'friends'],
    cities: [['Dubai', 4], ['Abu Dhabi', 1]],
    price: 58000,
    highlights: ['Burj Khalifa At the Top', 'Desert safari with BBQ dinner', 'Ferrari World, Abu Dhabi', 'Marina dhow cruise'],
    inclusions: ['5 nights in 4★ hotels with breakfast', 'Dubai visa processing', 'All transfers', 'Desert safari, dhow cruise and Burj Khalifa tickets', 'Abu Dhabi city tour'],
    exclusions: ['International flights', 'Tourism Dirham fee (paid at hotel)', 'Personal expenses'],
    itinerary: [
      ['Arrive', 'Airport pick-up; evening dhow cruise at the Marina.'],
      ['City tour', 'Old Dubai souks, abra ride, then Burj Khalifa at sunset.'],
      ['Desert safari', 'Free morning; afternoon dune bashing, camel ride and BBQ dinner.'],
      ['Free day', 'Aquaventure, IMG Worlds or shopping at Dubai Mall.'],
      ['Abu Dhabi', 'Sheikh Zayed Grand Mosque and Ferrari World.'],
      ['Depart', 'Airport transfer.'],
    ],
  },
  {
    destination: 'vietnam',
    title: 'Vietnam North to South: 9 Nights',
    summary: 'Hanoi, a Ha Long Bay cruise, Hoi An and Saigon in one flowing trip.',
    companions: ['friends', 'solo', 'couple'],
    cities: [['Hanoi', 2], ['Ha Long Bay', 1], ['Da Nang & Hoi An', 4], ['Ho Chi Minh City', 2]],
    price: 72000,
    highlights: ['Overnight Ha Long Bay cruise', 'Ba Na Hills Golden Bridge', 'Hoi An lantern night', 'Cu Chi tunnels'],
    inclusions: ['9 nights incl. 1 night cruise, with breakfast', 'Domestic flights Hanoi–Da Nang–Saigon', 'All transfers', 'Ba Na Hills and Cu Chi tours', 'e-Visa assistance'],
    exclusions: STD_EXCLUSIONS,
    itinerary: [
      ['Arrive Hanoi', 'Old Quarter walk and water-puppet show.'],
      ['Hanoi city', 'Ho Chi Minh Mausoleum, Temple of Literature, train street.'],
      ['Ha Long Bay', 'Board your cruise among the karsts; kayaking and cave visit.'],
      ['To Da Nang', 'Sunrise tai chi on deck, then fly to Da Nang.'],
      ['Ba Na Hills', 'Cable car to the Golden Bridge.'],
      ['Hoi An', 'Tailor shops, lantern-lit old town by night.'],
      ['Beach day', 'My Khe beach or a basket-boat ride.'],
      ['Saigon', 'Fly to Ho Chi Minh City; evening street-food tour.'],
      ['Cu Chi and Mekong', 'Cu Chi tunnels and a Mekong Delta boat ride.'],
      ['Depart', 'Airport transfer.'],
    ],
  },
  {
    destination: 'kenya',
    title: 'Great Migration Safari: 5 Nights',
    summary: 'Tented camp in the Mara during river-crossing season.',
    companions: ['family', 'couple', 'friends'],
    cities: [['Nairobi', 1], ['Maasai Mara', 3], ['Lake Naivasha', 1]],
    price: 295000,
    badge: 'Seasonal',
    highlights: ['6 game drives in the Maasai Mara', 'Optional hot-air balloon safari', 'Maasai village visit', 'Boat safari on Lake Naivasha'],
    inclusions: ['5 nights, full board on safari', 'Private 4x4 safari vehicle and guide', 'Park fees', 'Maasai village visit', 'Naivasha boat safari'],
    exclusions: [...STD_EXCLUSIONS, 'Hot-air balloon (optional)'],
    itinerary: [
      ['Arrive Nairobi', 'Airport pick-up; Giraffe Centre visit.'],
      ['Into the Mara', 'Drive to your tented camp; afternoon game drive.'],
      ['Full day in the Mara', 'River crossings with a picnic lunch.'],
      ['Mara morning', 'Optional sunrise balloon; Maasai village visit.'],
      ['Lake Naivasha', 'Drive to Naivasha; boat safari among hippos.'],
      ['Depart', 'Transfer to Nairobi airport.'],
    ],
  },
  {
    destination: 'sri-lanka',
    title: 'Sri Lanka Circuit: 6 Nights',
    summary: 'Sigiriya, Kandy, tea country and the beaches of Bentota.',
    companions: ['family', 'seniors', 'couple'],
    cities: [['Sigiriya', 1], ['Kandy', 2], ['Nuwara Eliya', 1], ['Bentota', 2]],
    price: 48000,
    highlights: ['Sigiriya rock fortress', 'Temple of the Tooth', 'Tea factory visit', 'Madu river safari'],
    inclusions: ['6 nights in 4★ hotels with breakfast and dinner', 'Private car with English-speaking chauffeur-guide', 'Entry tickets listed', 'ETA assistance'],
    exclusions: STD_EXCLUSIONS,
    itinerary: [
      ['Arrive Colombo', 'Drive to Sigiriya via Pinnawala.'],
      ['Sigiriya to Kandy', 'Climb Sigiriya, Dambulla cave temple, then Kandy.'],
      ['Kandy', 'Temple of the Tooth and the botanical gardens.'],
      ['Tea country', 'Scenic drive to Nuwara Eliya with a tea factory visit.'],
      ['To Bentota', 'Coast road to Bentota.'],
      ['Bentota', 'Madu river safari and turtle hatchery.'],
      ['Depart', 'Transfer to Colombo airport.'],
    ],
  },
  {
    destination: 'kerala',
    title: 'Kerala Backwaters and Hills: 5 Nights',
    summary: 'Munnar tea, Thekkady spice and a private houseboat night.',
    companions: ['family', 'seniors', 'couple'],
    cities: [['Munnar', 2], ['Thekkady', 1], ['Alleppey', 1], ['Kochi', 1]],
    price: 26500,
    badge: 'Bestseller',
    featured: true,
    highlights: ['Private houseboat with meals', 'Eravikulam National Park', 'Periyar boat ride', 'Kathakali in Kochi'],
    inclusions: ['5 nights incl. 1 houseboat night (all meals on board)', 'Private car and driver throughout', 'Breakfast daily', 'Kathakali show tickets'],
    exclusions: DOMESTIC_EXCLUSIONS,
    itinerary: [
      ['Kochi to Munnar', 'Pick-up at Kochi; drive past waterfalls to Munnar.'],
      ['Munnar', 'Eravikulam park, tea museum and Mattupetty dam.'],
      ['Thekkady', 'Spice plantation walk and Periyar lake boat ride.'],
      ['Alleppey houseboat', 'Board your private houseboat for a night on the backwaters.'],
      ['Kochi', 'Fort Kochi, Chinese fishing nets and a Kathakali show.'],
      ['Depart', 'Drop at Kochi airport.'],
    ],
  },
  {
    destination: 'kashmir',
    title: 'Kashmir Valley Honeymoon: 5 Nights',
    summary: 'Houseboat on Dal Lake, Gulmarg gondola and Pahalgam meadows.',
    companions: ['couple'],
    cities: [['Srinagar', 2], ['Gulmarg', 1], ['Pahalgam', 2]],
    price: 29900,
    highlights: ['Luxury houseboat night', 'Shikara ride at sunset', 'Gulmarg gondola phase 1', 'Betaab and Aru valleys'],
    inclusions: ['5 nights incl. 1 houseboat night, breakfast and dinner', 'Private car and driver', 'Shikara ride', 'Candle-light dinner and flower decoration'],
    exclusions: DOMESTIC_EXCLUSIONS,
    itinerary: [
      ['Arrive Srinagar', 'Check in to your houseboat; sunset shikara ride.'],
      ['Srinagar', 'Mughal gardens and the old city.'],
      ['Gulmarg', 'Gondola ride and meadow walks.'],
      ['Pahalgam', 'Drive via saffron fields to Pahalgam.'],
      ['Pahalgam valleys', 'Betaab, Aru and Chandanwari.'],
      ['Depart', 'Drop at Srinagar airport.'],
    ],
  },
  {
    destination: 'andaman',
    title: 'Andaman Island Hopper: 5 Nights',
    summary: 'Havelock beaches, a first scuba dive and sunsets on Neil Island.',
    companions: ['friends', 'couple', 'family'],
    cities: [['Port Blair', 1], ['Havelock', 3], ['Neil Island', 1]],
    price: 36500,
    highlights: ['Radhanagar Beach sunset', 'Try-scuba at Elephant Beach', 'Natural rock bridge', 'Cellular Jail light and sound show'],
    inclusions: ['5 nights in beach resorts with breakfast', 'Private ferry tickets', 'All transfers', 'One try-scuba dive'],
    exclusions: DOMESTIC_EXCLUSIONS,
    itinerary: [
      ['Arrive Port Blair', 'Corbyn’s Cove and the Cellular Jail show.'],
      ['Ferry to Havelock', 'Afternoon at Radhanagar Beach.'],
      ['Elephant Beach', 'Try-scuba and snorkelling.'],
      ['Havelock free day', 'Kalapathar beach or kayaking in the mangroves.'],
      ['Neil Island', 'Natural bridge, Bharatpur beach and sunset at Laxmanpur.'],
      ['Depart', 'Ferry to Port Blair and airport drop.'],
    ],
  },
  {
    destination: 'ladakh',
    title: 'Ladakh Road Trip: 7 Nights',
    summary: 'Leh, Nubra and Pangong with acclimatisation built in.',
    companions: ['friends', 'solo'],
    cities: [['Leh', 4], ['Nubra Valley', 2], ['Pangong', 1]],
    price: 39000,
    highlights: ['Khardung La pass', 'Bactrian camels at Hunder', 'Night at Pangong Tso', 'Thiksey and Hemis monasteries'],
    inclusions: ['7 nights in hotels and camps with breakfast and dinner', 'SUV with driver for the whole trip', 'Inner Line Permits', 'Oxygen cylinder in vehicle'],
    exclusions: DOMESTIC_EXCLUSIONS,
    itinerary: [
      ['Arrive Leh', 'Full rest day to acclimatise.'],
      ['Leh local', 'Shanti Stupa, Leh Palace and the market.'],
      ['Monasteries', 'Thiksey, Hemis and Shey.'],
      ['Nubra Valley', 'Over Khardung La to Hunder dunes.'],
      ['Nubra', 'Diskit Monastery and camel ride.'],
      ['Pangong', 'Via Shyok to Pangong Tso; lakeside camp.'],
      ['Back to Leh', 'Via Chang La.'],
      ['Depart', 'Airport drop.'],
    ],
  },
  {
    destination: 'bhutan',
    title: 'Bhutan Happiness Trail: 6 Nights',
    summary: 'Thimphu, Punakha and the Tiger’s Nest at an easy pace.',
    companions: ['seniors', 'family', 'couple'],
    cities: [['Thimphu', 2], ['Punakha', 2], ['Paro', 2]],
    price: 69000,
    highlights: ['Tiger’s Nest hike (pony option)', 'Punakha Dzong', 'Dochula Pass', 'Traditional hot-stone bath'],
    inclusions: ['6 nights with all meals', 'Private car and licensed guide', 'Permits and Sustainable Development Fee', 'Hot-stone bath'],
    exclusions: ['Flights to Paro or Bagdogra', 'Personal expenses and tips'],
    itinerary: [
      ['Arrive Paro', 'Drive to Thimphu.'],
      ['Thimphu', 'Buddha Dordenma, Memorial Chorten and the weekend market.'],
      ['Punakha', 'Over Dochula Pass to Punakha.'],
      ['Punakha', 'Punakha Dzong and the suspension bridge.'],
      ['Paro', 'Drive back to Paro; Rinpung Dzong.'],
      ['Tiger’s Nest', 'Hike to Paro Taktsang; hot-stone bath in the evening.'],
      ['Depart', 'Airport drop.'],
    ],
  },
  {
    destination: 'mauritius',
    title: 'Mauritius Island Escape: 6 Nights',
    summary: 'North-coast lagoons and south-west sunsets under Le Morne.',
    companions: ['couple', 'family'],
    cities: [['Grand Baie', 3], ['Le Morne', 3]],
    price: 105000,
    highlights: ['Île aux Cerfs catamaran', 'Chamarel and Black River Gorges', 'Dolphin swim', 'Beachfront resort stays'],
    inclusions: ['6 nights in 4★ beach resorts, half board', 'All transfers', 'Catamaran cruise with lunch', 'South island tour'],
    exclusions: STD_EXCLUSIONS,
    itinerary: [
      ['Arrive', 'Transfer to Grand Baie.'],
      ['North island', 'Port Louis, Pamplemousses garden and Caudan Waterfront.'],
      ['Île aux Cerfs', 'Full-day catamaran with BBQ lunch.'],
      ['To Le Morne', 'Transfer to the south-west coast.'],
      ['South island', 'Chamarel, Black River Gorges and Grand Bassin.'],
      ['Dolphins', 'Morning dolphin swim; afternoon free.'],
      ['Depart', 'Airport transfer.'],
    ],
  },
  {
    destination: 'santorini',
    title: 'Greek Island Hopping: 7 Nights',
    summary: 'Athens, Santorini and Mykonos by ferry.',
    companions: ['couple', 'friends'],
    cities: [['Athens', 2], ['Santorini', 3], ['Mykonos', 2]],
    price: 189000,
    highlights: ['Acropolis guided visit', 'Santorini caldera catamaran', 'Oia sunset', 'Mykonos Little Venice'],
    inclusions: ['7 nights in 3★/4★ hotels with breakfast', 'Ferry tickets', 'Airport and port transfers', 'Caldera catamaran cruise', 'Schengen visa assistance'],
    exclusions: STD_EXCLUSIONS,
    itinerary: [
      ['Arrive Athens', 'Evening in Plaka.'],
      ['Athens', 'Guided Acropolis and museum.'],
      ['Ferry to Santorini', 'Sunset in Oia.'],
      ['Caldera cruise', 'Catamaran with hot springs and BBQ.'],
      ['Santorini', 'Fira to Oia walk or beach day at Kamari.'],
      ['Ferry to Mykonos', 'Windmills and Little Venice.'],
      ['Mykonos', 'Beach day.'],
      ['Depart', 'Fly home via Athens.'],
    ],
  },
  {
    destination: 'rajasthan',
    title: 'Royal Rajasthan: 7 Nights',
    summary: 'Jaipur, Jodhpur, Udaipur and a desert camp in Jaisalmer.',
    companions: ['seniors', 'family', 'friends'],
    cities: [['Jaipur', 2], ['Jaisalmer', 2], ['Jodhpur', 1], ['Udaipur', 2]],
    price: 42000,
    highlights: ['Amber Fort', 'Sam sand dunes camp', 'Mehrangarh Fort', 'Lake Pichola boat ride'],
    inclusions: ['7 nights in heritage hotels and a desert camp, with breakfast', 'Private car and driver', 'Camel ride and cultural evening at the camp', 'Lake Pichola boat ride'],
    exclusions: DOMESTIC_EXCLUSIONS,
    itinerary: [
      ['Arrive Jaipur', 'Evening at Chokhi Dhani.'],
      ['Jaipur', 'Amber Fort, City Palace, Hawa Mahal.'],
      ['To Jaisalmer', 'Drive to the golden city.'],
      ['Desert', 'Jaisalmer Fort and a night at the Sam dunes.'],
      ['Jodhpur', 'Mehrangarh Fort and the blue city.'],
      ['To Udaipur', 'Via Ranakpur Jain temple.'],
      ['Udaipur', 'City Palace and Lake Pichola at sunset.'],
      ['Depart', 'Airport drop.'],
    ],
  },
  {
    destination: 'singapore',
    title: 'Singapore with Sentosa: 4 Nights',
    summary: 'Universal Studios, Night Safari and Gardens by the Bay.',
    companions: ['family'],
    cities: [['Singapore', 4]],
    price: 64000,
    highlights: ['Universal Studios Singapore', 'Night Safari', 'Gardens by the Bay', 'Sentosa cable car and Wings of Time'],
    inclusions: ['4 nights in a 4★ hotel with breakfast', 'Visa processing', 'All transfers', 'Tickets for all listed attractions'],
    exclusions: ['International flights', 'Personal expenses'],
    itinerary: [
      ['Arrive', 'Evening Night Safari.'],
      ['City and gardens', 'City tour and Gardens by the Bay light show.'],
      ['Universal Studios', 'Full day on Sentosa.'],
      ['Sentosa', 'Cable car, S.E.A. Aquarium and Wings of Time.'],
      ['Depart', 'Airport transfer.'],
    ],
  },
];
