/**
 * Freely licensed photos, clips and ambient sounds from Wikimedia Commons, used by the sample catalogue.
 * Each is hotlinked with its attribution. Replace them from Admin → Destinations with your own uploads any time.
 * Generated by hand-picking search results; every URL was checked when this file was written.
 */
export interface SeedAsset {
  url: string;
  credit: string;
}
export interface SeedMedia {
  cover: SeedAsset;
  gallery: SeedAsset[];
  video?: SeedAsset;
  audio?: SeedAsset;
}

export const SEED_MEDIA: Record<string, SeedMedia> = {
  "finland": {
    "cover": {
      "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/1/1e/Northern_lights_band_swirls_above_Vuopajanniemi%2C_Inari%2C_Lapland%2C_Finland%2C_2018_March.jpg/1280px-Northern_lights_band_swirls_above_Vuopajanniemi%2C_Inari%2C_Lapland%2C_Finland%2C_2018_March.jpg",
      "credit": "Ximonic (Simo Räsänen) · CC BY-SA 4.0 · Wikimedia Commons"
    },
    "gallery": [
      {
        "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/8/82/Gentle_but_wide_green_aurora_display_over_Tuikku%2C_Kittil%C3%A4%2C_Lapland%2C_Finland%2C_2023_September.jpg/1280px-Gentle_but_wide_green_aurora_display_over_Tuikku%2C_Kittil%C3%A4%2C_Lapland%2C_Finland%2C_2023_September.jpg",
        "credit": "Ximonic (Simo Räsänen) · CC BY-SA 4.0 · Wikimedia Commons"
      },
      {
        "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/8/80/Gentle_but_wide_green_aurora_display_over_Levi%2C_Kittil%C3%A4%2C_Lapland%2C_Finland%2C_2023_September_-_2.jpg/1280px-Gentle_but_wide_green_aurora_display_over_Levi%2C_Kittil%C3%A4%2C_Lapland%2C_Finland%2C_2023_September_-_2.jpg",
        "credit": "Ximonic (Simo Räsänen) · CC BY-SA 4.0 · Wikimedia Commons"
      }
    ],
    "video": {
      "url": "https://upload.wikimedia.org/wikipedia/commons/transcoded/4/4f/Aurora_timelapse.ogv/Aurora_timelapse.ogv.480p.vp9.webm",
      "credit": "Svamppierre · CC BY-SA 4.0 · Wikimedia Commons"
    }
  },
  "switzerland": {
    "cover": {
      "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/b/bc/Landscape_of_Bernese_Oberland_from_M%C3%A4nnlichen%2C_2012_August.JPG/1280px-Landscape_of_Bernese_Oberland_from_M%C3%A4nnlichen%2C_2012_August.JPG",
      "credit": "Ximonic (Simo Räsänen) · CC BY-SA 3.0 · Wikimedia Commons"
    },
    "gallery": [
      {
        "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/8/81/CH.BE.Grindelwald_2021-04-20_Moench-as-viewed-from-Sphinx-Jungfraujoch_1305_OrigX-R_22K.jpg/1280px-CH.BE.Grindelwald_2021-04-20_Moench-as-viewed-from-Sphinx-Jungfraujoch_1305_OrigX-R_22K.jpg",
        "credit": "NOTE: This image is a panorama consisting of multiple frames · CC BY-SA 4.0 · Wikimedia Commons"
      },
      {
        "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/7/73/CH.BE.Grindelwald_2021-04-20_Jungfraujoch_Sphinx-Observatory.jpg/1280px-CH.BE.Grindelwald_2021-04-20_Jungfraujoch_Sphinx-Observatory.jpg",
        "credit": "NOTE: This image is a panorama of Jungfraujoch Sphinx-Observ · CC BY-SA 4.0 · Wikimedia Commons"
      }
    ],
    "audio": {
      "url": "https://upload.wikimedia.org/wikipedia/commons/transcoded/6/65/Waidachswald_Oberschefflenz_Abend_20250616_2005.ogg/Waidachswald_Oberschefflenz_Abend_20250616_2005.ogg.mp3",
      "credit": "Evillan · CC0 · Wikimedia Commons"
    }
  },
  "japan": {
    "cover": {
      "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/4/4c/Series-N700a-Mt.Fuji.jpg/1280px-Series-N700a-Mt.Fuji.jpg",
      "credit": "MaedaAkihiko · CC BY-SA 4.0 · Wikimedia Commons"
    },
    "gallery": [
      {
        "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/1/19/Fujikyuko-Line_Series6000-6551_Mt.Fuji.jpg/1280px-Fujikyuko-Line_Series6000-6551_Mt.Fuji.jpg",
        "credit": "MaedaAkihiko · CC0 · Wikimedia Commons"
      },
      {
        "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/a/a2/View_towards_Mount_Fuji_from_Arakurayama_Sengen_Park_in_Fujiyoshida%2C_Yamanashi%2C_Japan%2C_2024_May_-_2.jpg/1280px-View_towards_Mount_Fuji_from_Arakurayama_Sengen_Park_in_Fujiyoshida%2C_Yamanashi%2C_Japan%2C_2024_May_-_2.jpg",
        "credit": "Ximonic (Simo Räsänen) · CC BY-SA 4.0 · Wikimedia Commons"
      }
    ],
    "video": {
      "url": "https://upload.wikimedia.org/wikipedia/commons/transcoded/4/4f/Fuji_aerial_stabilized_video.webm/Fuji_aerial_stabilized_video.webm.480p.vp9.webm",
      "credit": "Nesn · CC BY-SA 3.0 · Wikimedia Commons"
    },
    "audio": {
      "url": "https://upload.wikimedia.org/wikipedia/commons/transcoded/6/64/Japanese_rin_played_as_friction_idiophone.ogg/Japanese_rin_played_as_friction_idiophone.ogg.mp3",
      "credit": "MichaelMaggs · CC BY-SA 4.0 · Wikimedia Commons"
    }
  },
  "maldives": {
    "cover": {
      "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/3/3b/Diamonds_Thudufushi_Beach_and_Water_Villas%2C_May_2017_-04.jpg/1280px-Diamonds_Thudufushi_Beach_and_Water_Villas%2C_May_2017_-04.jpg",
      "credit": "Martin Falbisoner · CC BY-SA 4.0 · Wikimedia Commons"
    },
    "gallery": [
      {
        "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/a/a5/Thatched-roof_villa_in_the_Maldive_Islands.jpg/1280px-Thatched-roof_villa_in_the_Maldive_Islands.jpg",
        "credit": "Godot13 · CC BY-SA 4.0 · Wikimedia Commons"
      },
      {
        "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/2/22/Diamonds_Thudufushi_Beach_and_Water_Villas%2C_May_2017_-09.jpg/1280px-Diamonds_Thudufushi_Beach_and_Water_Villas%2C_May_2017_-09.jpg",
        "credit": "Martin Falbisoner · CC BY-SA 4.0 · Wikimedia Commons"
      }
    ],
    "audio": {
      "url": "https://upload.wikimedia.org/wikipedia/commons/transcoded/6/64/Ocean_Waves_on_a_Tropical_Beach.ogg/Ocean_Waves_on_a_Tropical_Beach.ogg.mp3",
      "credit": "Jarrod stanley · CC0 · Wikimedia Commons"
    }
  },
  "bali": {
    "cover": {
      "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/c/c0/Brantan_Bali_Pura-Ulun-Danu-Bratan-01.jpg/1280px-Brantan_Bali_Pura-Ulun-Danu-Bratan-01.jpg",
      "credit": "CEphoto, Uwe Aranas · CC BY-SA 3.0 · Wikimedia Commons"
    },
    "gallery": [
      {
        "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/4/4f/Besakih_Bali_Indonesia_Pura-Besakih-02.jpg/1280px-Besakih_Bali_Indonesia_Pura-Besakih-02.jpg",
        "credit": "CEphoto, Uwe Aranas · CC BY-SA 3.0 · Wikimedia Commons"
      },
      {
        "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/5/54/Goa_Gajah_temple%2C_Bedulu%2C_Bali%2C_Indonesia%2C_20220824_0929_0544.jpg/1280px-Goa_Gajah_temple%2C_Bedulu%2C_Bali%2C_Indonesia%2C_20220824_0929_0544.jpg",
        "credit": "Jakub Hałun · CC BY-SA 4.0 · Wikimedia Commons"
      }
    ],
    "audio": {
      "url": "https://upload.wikimedia.org/wikipedia/commons/transcoded/e/eb/RainforestDawnChorus_Selaliparai_DM.ogg/RainforestDawnChorus_Selaliparai_DM.ogg.mp3",
      "credit": "DivyaCM · CC BY 4.0 · Wikimedia Commons"
    }
  },
  "thailand": {
    "cover": {
      "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/0/09/Isla_Phi_Phi_Lay%2C_Tailandia%2C_2013-08-19%2C_DD_04.JPG/1280px-Isla_Phi_Phi_Lay%2C_Tailandia%2C_2013-08-19%2C_DD_04.JPG",
      "credit": "Diego Delso · CC BY-SA 3.0 · Wikimedia Commons"
    },
    "gallery": [
      {
        "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/1/1e/West_Rai_Leh_%283%29.jpg/1280px-West_Rai_Leh_%283%29.jpg",
        "credit": "Krzysztof Golik · CC BY-SA 4.0 · Wikimedia Commons"
      },
      {
        "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/5/59/West_Rai_Leh_%2811%29.jpg/1280px-West_Rai_Leh_%2811%29.jpg",
        "credit": "Krzysztof Golik · CC BY-SA 4.0 · Wikimedia Commons"
      }
    ],
    "video": {
      "url": "https://upload.wikimedia.org/wikipedia/commons/transcoded/7/76/Railay_Beach_P1120783.ogv/Railay_Beach_P1120783.ogv.480p.vp9.webm",
      "credit": "deror_avi · CC BY-SA 3.0 · Wikimedia Commons"
    },
    "audio": {
      "url": "https://upload.wikimedia.org/wikipedia/commons/transcoded/6/64/Ocean_Waves_on_a_Tropical_Beach.ogg/Ocean_Waves_on_a_Tropical_Beach.ogg.mp3",
      "credit": "Jarrod stanley · CC0 · Wikimedia Commons"
    }
  },
  "singapore": {
    "cover": {
      "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/8/8c/Marina_Bay_Sands_and_illuminated_polyhedral_building_Louis_Vuitton_over_the_water_at_blue_hour_with_pink_clouds_in_Singapore.jpg/1280px-Marina_Bay_Sands_and_illuminated_polyhedral_building_Louis_Vuitton_over_the_water_at_blue_hour_with_pink_clouds_in_Singapore.jpg",
      "credit": "Basile Morin · CC BY-SA 4.0 · Wikimedia Commons"
    },
    "gallery": [
      {
        "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/7/7e/Cricket_match_and_Marina_Bay_Sands_Hotel_in_Singapore.jpg/1280px-Cricket_match_and_Marina_Bay_Sands_Hotel_in_Singapore.jpg",
        "credit": "Basile Morin · CC BY-SA 4.0 · Wikimedia Commons"
      },
      {
        "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/f/f3/ArtScience_Museum%2C_Marina_Bay_Sands%2C_Singapore.jpg/1280px-ArtScience_Museum%2C_Marina_Bay_Sands%2C_Singapore.jpg",
        "credit": "Basile Morin · CC BY-SA 4.0 · Wikimedia Commons"
      }
    ],
    "video": {
      "url": "https://upload.wikimedia.org/wikipedia/commons/transcoded/6/6a/A_drone_video_in_Singapore.webm/A_drone_video_in_Singapore.webm.480p.vp9.webm",
      "credit": "Exec8 · CC BY-SA 4.0 · Wikimedia Commons"
    }
  },
  "dubai": {
    "cover": {
      "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/3/3d/Burj_Khalifa_Night_View_01.jpg/1280px-Burj_Khalifa_Night_View_01.jpg",
      "credit": "Sergei Gussev · CC BY 2.0 · Wikimedia Commons"
    },
    "gallery": [
      {
        "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/2/2a/Burj_Khalifa_Night_View_03.jpg/1280px-Burj_Khalifa_Night_View_03.jpg",
        "credit": "Sergei Gussev · CC BY 2.0 · Wikimedia Commons"
      },
      {
        "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/4/48/Burj_Khalifa_from_the_sea%2C_Dubai.jpg/1280px-Burj_Khalifa_from_the_sea%2C_Dubai.jpg",
        "credit": "Jpbowen · CC BY-SA 4.0 · Wikimedia Commons"
      }
    ]
  },
  "vietnam": {
    "cover": {
      "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/2/28/View_of_sea_from_Titov_Island%2C_Ha_Long_Bay%2C_Vietnam%2C_20240128_1337_3732.jpg/1280px-View_of_sea_from_Titov_Island%2C_Ha_Long_Bay%2C_Vietnam%2C_20240128_1337_3732.jpg",
      "credit": "Jakub Hałun · CC BY 4.0 · Wikimedia Commons"
    },
    "gallery": [
      {
        "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/7/7b/Ha-Long-Bay3.jpg/1280px-Ha-Long-Bay3.jpg",
        "credit": "Steven C. Price · CC BY-SA 4.0 · Wikimedia Commons"
      }
    ],
    "video": {
      "url": "https://upload.wikimedia.org/wikipedia/commons/transcoded/b/be/Ha_Long_Bay%2C_Vietnam_-_Dec_2024.webm/Ha_Long_Bay%2C_Vietnam_-_Dec_2024.webm.480p.vp9.webm",
      "credit": "പയ്യൻ · CC BY-SA 4.0 · Wikimedia Commons"
    }
  },
  "kenya": {
    "cover": {
      "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/8/89/Three_giraffes_01.jpg/1280px-Three_giraffes_01.jpg",
      "credit": "Byrdyak · CC BY-SA 4.0 · Wikimedia Commons"
    },
    "gallery": [
      {
        "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/7/75/Three_zebras_in_Masai_Mara_National_Park%2C_Kenya.jpg/1280px-Three_zebras_in_Masai_Mara_National_Park%2C_Kenya.jpg",
        "credit": "Volodymyr Burdiak · CC BY-SA 4.0 · Wikimedia Commons"
      }
    ],
    "video": {
      "url": "https://upload.wikimedia.org/wikipedia/commons/transcoded/4/45/Wildebeest_herd_running_in_the_Maasai_Mara_National_Reserve.webm/Wildebeest_herd_running_in_the_Maasai_Mara_National_Reserve.webm.480p.vp9.webm",
      "credit": "Lebu Ayiga · CC BY 4.0 · Wikimedia Commons"
    }
  },
  "sri-lanka": {
    "cover": {
      "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/c/c7/Sigiriya.jpg/1280px-Sigiriya.jpg",
      "credit": "Bernard Gagnon · CC BY-SA 3.0 · Wikimedia Commons"
    },
    "gallery": [
      {
        "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/1/1f/Sigiriya_Luftbild_%2829781064900%29.jpg/1280px-Sigiriya_Luftbild_%2829781064900%29.jpg",
        "credit": "dronepicr · CC BY 2.0 · Wikimedia Commons"
      },
      {
        "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/7/7b/SriLanka_Sigiriya_gardens.jpg/1280px-SriLanka_Sigiriya_gardens.jpg",
        "credit": "Shoka at English Wikipedia · CC BY-SA 3.0 · Wikimedia Commons"
      }
    ],
    "audio": {
      "url": "https://upload.wikimedia.org/wikipedia/commons/transcoded/e/eb/RainforestDawnChorus_Selaliparai_DM.ogg/RainforestDawnChorus_Selaliparai_DM.ogg.mp3",
      "credit": "DivyaCM · CC BY 4.0 · Wikimedia Commons"
    }
  },
  "malaysia": {
    "cover": {
      "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/1/17/Kuala_Lumpur_Malaysia_Petronas-Twin-Towers-01.jpg/1280px-Kuala_Lumpur_Malaysia_Petronas-Twin-Towers-01.jpg",
      "credit": "CEphoto, Uwe Aranas · CC BY-SA 3.0 · Wikimedia Commons"
    },
    "gallery": [
      {
        "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/8/8f/2016_Kuala_Lumpur%2C_Petronas_Towers_%2827%29.jpg/1280px-2016_Kuala_Lumpur%2C_Petronas_Towers_%2827%29.jpg",
        "credit": "Marcin Konsek · CC BY-SA 4.0 · Wikimedia Commons"
      }
    ]
  },
  "mauritius": {
    "cover": {
      "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/1/18/Le_Morne_Peninsula_in_Mauritius_%2853697779236%29.jpg/1280px-Le_Morne_Peninsula_in_Mauritius_%2853697779236%29.jpg",
      "credit": "dronepicr · CC BY 2.0 · Wikimedia Commons"
    },
    "gallery": [
      {
        "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/e/e7/Sunbathing_at_Le_Morne_Beach_in_Mauritius_%2853697787846%29.jpg/1280px-Sunbathing_at_Le_Morne_Beach_in_Mauritius_%2853697787846%29.jpg",
        "credit": "dronepicr · CC BY 2.0 · Wikimedia Commons"
      },
      {
        "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/5/56/Le_Morne_mountain_morning_shadow.jpg/1280px-Le_Morne_mountain_morning_shadow.jpg",
        "credit": "Gavish Barosee · CC BY-SA 4.0 · Wikimedia Commons"
      }
    ],
    "video": {
      "url": "https://upload.wikimedia.org/wikipedia/commons/transcoded/a/a9/Windy_day_on_Mauritius_shortly_before_monsoon_storm.webm/Windy_day_on_Mauritius_shortly_before_monsoon_storm.webm.480p.vp9.webm",
      "credit": "Jan Czeczotka · CC BY-SA 4.0 · Wikimedia Commons"
    },
    "audio": {
      "url": "https://upload.wikimedia.org/wikipedia/commons/transcoded/6/64/Ocean_Waves_on_a_Tropical_Beach.ogg/Ocean_Waves_on_a_Tropical_Beach.ogg.mp3",
      "credit": "Jarrod stanley · CC0 · Wikimedia Commons"
    }
  },
  "kerala": {
    "cover": {
      "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/4/4e/Kerala_backwaters%2C_Houseboats%2C_India.jpg/1280px-Kerala_backwaters%2C_Houseboats%2C_India.jpg",
      "credit": "Vyacheslav Argenberg · CC BY 4.0 · Wikimedia Commons"
    },
    "gallery": [
      {
        "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/a/a6/Kerala_backwaters%2C_Canal%2C_Palm_trees%2C_India.jpg/1280px-Kerala_backwaters%2C_Canal%2C_Palm_trees%2C_India.jpg",
        "credit": "Vyacheslav Argenberg · CC BY 4.0 · Wikimedia Commons"
      },
      {
        "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/c/c6/Kerala_backwaters%2C_Palm_trees%2C_India.jpg/1280px-Kerala_backwaters%2C_Palm_trees%2C_India.jpg",
        "credit": "Vyacheslav Argenberg · CC BY 4.0 · Wikimedia Commons"
      }
    ],
    "video": {
      "url": "https://upload.wikimedia.org/wikipedia/commons/transcoded/6/64/Monsoon_Rain_in_Kerala_20230928_134308.ogg/Monsoon_Rain_in_Kerala_20230928_134308.ogg.480p.vp9.webm",
      "credit": "Ramesh Kunnappully · CC BY-SA 4.0 · Wikimedia Commons"
    }
  },
  "rajasthan": {
    "cover": {
      "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/5/5c/20191207_City_Palace%2C_Udaipur_1701_7325.jpg/1280px-20191207_City_Palace%2C_Udaipur_1701_7325.jpg",
      "credit": "Jakub Hałun · CC BY-SA 4.0 · Wikimedia Commons"
    },
    "gallery": [
      {
        "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/a/a0/City_Palace%2C_Udaipur%2C_20191207_1542_7282.jpg/1280px-City_Palace%2C_Udaipur%2C_20191207_1542_7282.jpg",
        "credit": "Jakub Hałun · CC BY-SA 4.0 · Wikimedia Commons"
      },
      {
        "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/0/07/Taj_Lake_Palace_Udaipur_from_City_Palace.jpg/1280px-Taj_Lake_Palace_Udaipur_from_City_Palace.jpg",
        "credit": "Navneet Sharma · CC BY-SA 4.0 · Wikimedia Commons"
      }
    ]
  },
  "kashmir": {
    "cover": {
      "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/e/e1/Dal_Lake_Hazratbal_Srinagar.jpg/1280px-Dal_Lake_Hazratbal_Srinagar.jpg",
      "credit": "Suhail Skindar Sofi · CC BY-SA 4.0 · Wikimedia Commons"
    },
    "gallery": [
      {
        "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/1/17/Lake_Geneva_from_Chillon_Castle.jpg/1280px-Lake_Geneva_from_Chillon_Castle.jpg",
        "credit": "Dmitry A. Mottl · CC BY-SA 4.0 · Wikimedia Commons"
      },
      {
        "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/1/17/Dal_Lake%2C_Srinagar%2C_Jammu_and_Kashmir.jpg/1280px-Dal_Lake%2C_Srinagar%2C_Jammu_and_Kashmir.jpg",
        "credit": "Dashrathgoyal85 · CC BY-SA 4.0 · Wikimedia Commons"
      }
    ],
    "audio": {
      "url": "https://upload.wikimedia.org/wikipedia/commons/transcoded/6/65/Waidachswald_Oberschefflenz_Abend_20250616_2005.ogg/Waidachswald_Oberschefflenz_Abend_20250616_2005.ogg.mp3",
      "credit": "Evillan · CC0 · Wikimedia Commons"
    }
  },
  "andaman": {
    "cover": {
      "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/5/51/Havelock_Island%2C_Mangrove_tree_on_the_beach%2C_Andaman_Islands.jpg/1280px-Havelock_Island%2C_Mangrove_tree_on_the_beach%2C_Andaman_Islands.jpg",
      "credit": "Vyacheslav Argenberg · CC BY 4.0 · Wikimedia Commons"
    },
    "gallery": [
      {
        "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/1/19/Havelock_Island%2C_Sandy_lagoon%2C_Andaman_Islands.jpg/1280px-Havelock_Island%2C_Sandy_lagoon%2C_Andaman_Islands.jpg",
        "credit": "Vyacheslav Argenberg · CC BY 4.0 · Wikimedia Commons"
      },
      {
        "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/3/32/Andaman_Sea%2C_Andaman_Islands.jpg/1280px-Andaman_Sea%2C_Andaman_Islands.jpg",
        "credit": "Vyacheslav Argenberg · CC BY 4.0 · Wikimedia Commons"
      }
    ],
    "video": {
      "url": "https://upload.wikimedia.org/wikipedia/commons/transcoded/7/74/Abudefduf_in_Andaman_Sea_02.ogv/Abudefduf_in_Andaman_Sea_02.ogv.480p.vp9.webm",
      "credit": "Nicor · CC BY-SA 3.0 · Wikimedia Commons"
    },
    "audio": {
      "url": "https://upload.wikimedia.org/wikipedia/commons/transcoded/6/64/Ocean_Waves_on_a_Tropical_Beach.ogg/Ocean_Waves_on_a_Tropical_Beach.ogg.mp3",
      "credit": "Jarrod stanley · CC0 · Wikimedia Commons"
    }
  },
  "bhutan": {
    "cover": {
      "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/4/46/Bhutan-Paro-136-Taktshang-Tigernest-gje.jpg/1280px-Bhutan-Paro-136-Taktshang-Tigernest-gje.jpg",
      "credit": "Gerd Eichmann · CC BY-SA 4.0 · Wikimedia Commons"
    },
    "gallery": [
      {
        "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/3/3d/Taktsang_Monastery%2C_Bhutan_03.jpg/1280px-Taktsang_Monastery%2C_Bhutan_03.jpg",
        "credit": "Bernard Gagnon · CC BY-SA 4.0 · Wikimedia Commons"
      },
      {
        "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/9/96/Taktsang_Monastery%2C_Bhutan_01.jpg/1280px-Taktsang_Monastery%2C_Bhutan_01.jpg",
        "credit": "Bernard Gagnon · CC BY-SA 4.0 · Wikimedia Commons"
      }
    ],
    "video": {
      "url": "https://upload.wikimedia.org/wikipedia/commons/transcoded/0/07/Ethnic_Festival_in_Paro_%28Bhutan%29_1.webm/Ethnic_Festival_in_Paro_%28Bhutan%29_1.webm.480p.vp9.webm",
      "credit": "Виктор Пинчук · CC BY 4.0 · Wikimedia Commons"
    }
  },
  "ladakh": {
    "cover": {
      "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/f/f4/Phyang_Monastery_01.jpg/1280px-Phyang_Monastery_01.jpg",
      "credit": "Bernard Gagnon · CC BY-SA 4.0 · Wikimedia Commons"
    },
    "gallery": [
      {
        "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/f/fb/Fields_Zangla_Zanskar_River_Ladakh_Jun24_A7CR_00981.jpg/1280px-Fields_Zangla_Zanskar_River_Ladakh_Jun24_A7CR_00981.jpg",
        "credit": "This Photo was taken by Timothy A. Gonsalves. Feel free to u · CC BY-SA 4.0 · Wikimedia Commons"
      }
    ],
    "video": {
      "url": "https://upload.wikimedia.org/wikipedia/commons/transcoded/a/a3/PANGONG_LAKE_%2C_LEH_LADAKH.webm/PANGONG_LAKE_%2C_LEH_LADAKH.webm.480p.vp9.webm",
      "credit": "Tseringangchuk502 · CC BY-SA 4.0 · Wikimedia Commons"
    },
    "audio": {
      "url": "https://upload.wikimedia.org/wikipedia/commons/transcoded/e/e5/Singing_bowl.ogg/Singing_bowl.ogg.mp3",
      "credit": "Юкатан · CC BY-SA 3.0 · Wikimedia Commons"
    }
  },
  "santorini": {
    "cover": {
      "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/2/27/1000_Three_domes_of_Oia_in_Santorini_Photo_by_Giles_Laurent.jpg/1280px-1000_Three_domes_of_Oia_in_Santorini_Photo_by_Giles_Laurent.jpg",
      "credit": "Giles Laurent · CC BY-SA 4.0 · Wikimedia Commons"
    },
    "gallery": [
      {
        "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/a/af/07-17-2012_-_Oia_-_Santorini_-_Greece_-_15.jpg/1280px-07-17-2012_-_Oia_-_Santorini_-_Greece_-_15.jpg",
        "credit": "Norbert Nagel · CC BY-SA 3.0 · Wikimedia Commons"
      },
      {
        "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/7/79/Oia_-_Santorini_-_Greece_-_16.jpg/1280px-Oia_-_Santorini_-_Greece_-_16.jpg",
        "credit": "Norbert Nagel · CC BY-SA 3.0 · Wikimedia Commons"
      }
    ],
    "audio": {
      "url": "https://upload.wikimedia.org/wikipedia/commons/transcoded/6/64/Ocean_Waves_on_a_Tropical_Beach.ogg/Ocean_Waves_on_a_Tropical_Beach.ogg.mp3",
      "credit": "Jarrod stanley · CC0 · Wikimedia Commons"
    }
  }
};
